name: Test

on:
  push:
    branches:
      - '*'

jobs:
  runnerx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download and flutter
        run: |
          chmod +x setup.sh
          ./setup.sh -c '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' -n 'any' -a '${{ runner.arch }}' stable
        shell: bash
